-- MySQL Script generated by MySQL Workbench
-- Thu Mar 13 00:45:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente Pessoa Física`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente Pessoa Física` (
  `idCliente Pessoa Física` INT NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente Pessoa Física`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente Pessoa Jurídica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente Pessoa Jurídica` (
  `idCliente Pessoa Jurídica` INT NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente Pessoa Jurídica`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Identificação` VARCHAR(45) NULL,
  `Cliente Pessoa Física_idCliente Pessoa Física` INT NOT NULL,
  `Cliente Pessoa Jurídica_idCliente Pessoa Jurídica` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Cliente Pessoa Física_idCliente Pessoa Física`, `Cliente Pessoa Jurídica_idCliente Pessoa Jurídica`),
  INDEX `fk_Cliente_Cliente Pessoa Física1_idx` (`Cliente Pessoa Física_idCliente Pessoa Física` ASC) VISIBLE,
  INDEX `fk_Cliente_Cliente Pessoa Jurídica1_idx` (`Cliente Pessoa Jurídica_idCliente Pessoa Jurídica` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cliente Pessoa Física1`
    FOREIGN KEY (`Cliente Pessoa Física_idCliente Pessoa Física`)
    REFERENCES `mydb`.`Cliente Pessoa Física` (`idCliente Pessoa Física`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Cliente Pessoa Jurídica1`
    FOREIGN KEY (`Cliente Pessoa Jurídica_idCliente Pessoa Jurídica`)
    REFERENCES `mydb`.`Cliente Pessoa Jurídica` (`idCliente Pessoa Jurídica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `Código de rastreio` VARCHAR(45) NOT NULL,
  `Status entrega` DATE NULL,
  PRIMARY KEY (`idEntrega`),
  UNIQUE INDEX `Código de rastreio_UNIQUE` (`Código de rastreio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Status do Pedido` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Frete` FLOAT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `Entrega_idEntrega`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Entrega1_idx` (`Entrega_idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`Entrega_idEntrega`)
    REFERENCES `mydb`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornece` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disponibilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disponibilidade` (
  `Estoque_idEstoque` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Estoque_idEstoque`, `Produto_idProduto`),
  INDEX `fk_Estoque_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Estoque_has_Produto_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_has_Produto_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação Produto -> Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relação Produto -> Pedido` (
  `Pedido_idPedido` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Produto_idProduto`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedor (Terceiro)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendedor (Terceiro)` (
  `idTerceiro - Vendedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerceiro - Vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação Produto -> Vendedor (terceiro)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relação Produto -> Vendedor (terceiro)` (
  `Terceiro - Vendedor_idTerceiro - Vendedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Terceiro - Vendedor_idTerceiro - Vendedor`, `Produto_idProduto`),
  INDEX `fk_Terceiro - Vendedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1_idx` (`Terceiro - Vendedor_idTerceiro - Vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1`
    FOREIGN KEY (`Terceiro - Vendedor_idTerceiro - Vendedor`)
    REFERENCES `mydb`.`Vendedor (Terceiro)` (`idTerceiro - Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `Forma de pagamento` VARCHAR(45) NULL,
  `Status do pagamento` VARCHAR(45) NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Pedido_Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idPagamento`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`, `Pedido_Entrega_idEntrega`),
  INDEX `fk_Pagamento_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC, `Pedido_Entrega_idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_Entrega_idEntrega`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente` , `Entrega_idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartão` (
  `idCartão` INT NOT NULL,
  `Data do pagamento` DATE NULL,
  `Tipo de pagamento (Deb/Créd)` VARCHAR(45) NOT NULL,
  `Dados do cartão` VARCHAR(45) NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Forma de pagamento (Link ou maquininha)` VARCHAR(45) NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `Pagamento_Pedido_idPedido` INT NOT NULL,
  `Pagamento_Pedido_Cliente_idCliente` INT NOT NULL,
  `Pagamento_Pedido_Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idCartão`, `Pagamento_idPagamento`, `Pagamento_Pedido_idPedido`, `Pagamento_Pedido_Cliente_idCliente`, `Pagamento_Pedido_Entrega_idEntrega`),
  UNIQUE INDEX `Tipo de pagamento (Deb/Créd)_UNIQUE` (`Tipo de pagamento (Deb/Créd)` ASC) VISIBLE,
  UNIQUE INDEX `Dados do cartão_UNIQUE` (`Dados do cartão` ASC) VISIBLE,
  UNIQUE INDEX `Valor_UNIQUE` (`Valor` ASC) VISIBLE,
  INDEX `fk_Cartão_Pagamento1_idx` (`Pagamento_idPagamento` ASC, `Pagamento_Pedido_idPedido` ASC, `Pagamento_Pedido_Cliente_idCliente` ASC, `Pagamento_Pedido_Entrega_idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Cartão_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento` , `Pagamento_Pedido_idPedido` , `Pagamento_Pedido_Cliente_idCliente` , `Pagamento_Pedido_Entrega_idEntrega`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento` , `Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_Entrega_idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pix` (
  `idPix` INT NOT NULL,
  `Data do pagamento` DATE NULL,
  `Dados do pagante` VARCHAR(45) NOT NULL,
  `Comprovante de pagamento` VARCHAR(45) NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `Pagamento_Pedido_idPedido` INT NOT NULL,
  `Pagamento_Pedido_Cliente_idCliente` INT NOT NULL,
  `Pagamento_Pedido_Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idPix`, `Pagamento_idPagamento`, `Pagamento_Pedido_idPedido`, `Pagamento_Pedido_Cliente_idCliente`, `Pagamento_Pedido_Entrega_idEntrega`),
  UNIQUE INDEX `Dados do pagante_UNIQUE` (`Dados do pagante` ASC) VISIBLE,
  UNIQUE INDEX `Comprovante de pagamento_UNIQUE` (`Comprovante de pagamento` ASC) VISIBLE,
  UNIQUE INDEX `Valor_UNIQUE` (`Valor` ASC) VISIBLE,
  INDEX `fk_Pix_Pagamento1_idx` (`Pagamento_idPagamento` ASC, `Pagamento_Pedido_idPedido` ASC, `Pagamento_Pedido_Cliente_idCliente` ASC, `Pagamento_Pedido_Entrega_idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Pix_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento` , `Pagamento_Pedido_idPedido` , `Pagamento_Pedido_Cliente_idCliente` , `Pagamento_Pedido_Entrega_idEntrega`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento` , `Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_Entrega_idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boleto` (
  `idBoleto` INT NOT NULL,
  `Data de vencimento` DATE NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Parcelamento` INT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `Pagamento_Pedido_idPedido` INT NOT NULL,
  `Pagamento_Pedido_Cliente_idCliente` INT NOT NULL,
  `Pagamento_Pedido_Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idBoleto`, `Pagamento_idPagamento`, `Pagamento_Pedido_idPedido`, `Pagamento_Pedido_Cliente_idCliente`, `Pagamento_Pedido_Entrega_idEntrega`),
  UNIQUE INDEX `Valor_UNIQUE` (`Valor` ASC) VISIBLE,
  INDEX `fk_Boleto_Pagamento1_idx` (`Pagamento_idPagamento` ASC, `Pagamento_Pedido_idPedido` ASC, `Pagamento_Pedido_Cliente_idCliente` ASC, `Pagamento_Pedido_Entrega_idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Boleto_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento` , `Pagamento_Pedido_idPedido` , `Pagamento_Pedido_Cliente_idCliente` , `Pagamento_Pedido_Entrega_idEntrega`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento` , `Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_Entrega_idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
